### ISSUE TITLE
`T2BayesianBlocks.outlier()` should flag only blocks with one point as outliers

### ISSUE THREAD

**Issue by JannisNe** [AmpelProject/Ampel-HU-astro#19]
Curretly the code fails with 

```
 Traceback (most recent call last):
   File "/Users/jannisnecker/opt/miniconda3/envs/airflares_local_hu/lib/python3.10/site-packages/ampel/t2/T2Worker.py", line 614, in run_t2_unit
     ret = t2_unit.process(*args)
   File "/Users/jannisnecker/Software/Ampel-HU-astro/ampel/contrib/hu/t2/T2BayesianBlocks.py", line 733, in process
     baye_block = self.outliers(
   File "/Users/jannisnecker/Software/Ampel-HU-astro/ampel/contrib/hu/t2/T2BayesianBlocks.py", line 188, in outliers
     baye_block["Npoints"][value[0]] == 1
 ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Blocks should only be flagged as outliers if they contain one datapoint in [L185](https://github.com/AmpelProject/Ampel-HU-astro/blob/c67d00db386c605215bfd3a5975d7c7a329a75b2/ampel/contrib/hu/t2/T2BayesianBlocks.py#L185). 
The breaking change was introduced in [this commit](https://github.com/AmpelProject/Ampel-HU-astro/commit/5c6793da4b7ea745c7e7a7d837eebc824e52d0fb) where the number is changed to 5. 
@simeonreusch could you check if this is needed for ZTF as indicated in the commit message?

**Comment by simeonreusch** [comment]
Will check. My strong suspicion is that it‘s not necessary.
